spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            first:
                url: jdbc:mysql://120.79.193.54/brm-admin?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
                username: root
                password: 123456
            second:
                url: jdbc:mysql://120.79.193.54/brm-admin?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
                username: root
                password: 123456
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
    redis:
            database: 0
            host:  120.79.193.54
            password: brmredis
            port: 6379
            timeout: 6000  # 连接超时时长（毫秒）
            pool:
                max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
                max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-idle: 20      # 连接池中的最大空闲连接
                min-idle: 5       # 连接池中的最小空闲连接

#微信配置
wx:
  appId: wx5b0fde4c84dcf033
  appSecret: f0ada9932b426c64c9bcdaec4f35741c
  mchId: 1498925632
  partnerKey: fjdkl44fdgba4d54v1v6d5s4f46d41an
  certPath: xxxx
  domain: shop.3zhit.com

#支付宝配置
alipay:
  appId: 2018030602323975
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCXKPmONbuqhfOhxLHTLClprFdTNjQ/3TnrsPe3729kTlkhQS+zZOVOvFDeOiNa9SKWlwMJqgi67qJKfLdKnzVLpL/uiA0Y2NZc6oETuKctmp6ZvJmJWTeolkTeyv5jpl7gNmDsFvHsd9b1XJq8p+itP9kEdDb56AGVW1Tuv0uksncPVE5qIzzPQ61hiv5XIrJAQjmODtaY8DwUsbfwVsB3QNjwUrb6SVBQ7WBYPs4vU5xkZl9zJ3IyVjfm+NZI4dmFiUb+6PRPth45aGyv1VvhLeJtvTtjihqf3yE0visalbh/UiBRyWBb6GYBPZxgUj4FMYcGIcymRI4/AKoIcA6ZAgMBAAECggEBAIQiRUOSpOGDBl06W1eFGw5MoGkU0Mei0qa8o04d9vlvo2n2WYQvhmM1KluX5p/z+LA6gWVJRShiwWrrai3IzgW5li0ksI4vvfKq6voaR8kNh+ZLfssZOhYchUdbmtPw8q572m2GASP7/eOtd3XCMRqA3WuPSx9ZN0kf9TZd8fmcz5pBmAVO5hlS/CiqI4zNDTC+53aXnYvqq+7t+qa9KVwAut4i0+UUet5RPm+fwVxmxlpBGWB0B8EbLEc3hB80eBnjXAazyEz0XGnKqoPqXTNAs8zB/pILJhDfuRARqWQCpNuldM48tqTulUcUBt3mABQBf4VTHpYUv7YOD7h8miECgYEAxf1mKSIAmrmNIcMRD7f6/ipSbcbiOhdJDGeuZ8Mb8/7Jv13DhixYUphtGchSoyD7ZXC3Q+k9EC9bPtYygHW0THSqnIduJnuK2QTOaRlYZ6A4VuH6t/uiNsSXY0D971T6gBakMXnaU+2OQQhUbsMkf5CBSm7V4ASMN1tQgx/BlVMCgYEAw3MFDPorzjLFttv490caJUcJrXAqMpn/TwVODsUzSns1Zd3JM9fzEJVy0Ay7JtGtdtTDbsGEY7Rj+uDISVqqLQPgmwyynOur0X5bOBwYx6Y++mphQrewuoM0QAI3l/GYdro2h1VDgIl/hzi3o5Pl3IMNdG+/BO+RIeWFcQ8qAuMCgYEApdS0eMdOEkpP93NXGv9Sbwgrul7WpSlTudwtrCMzio5hlLOITR1fbO7Wkr3C2XeKmVBrb6ovxxqjJmJqMkZkGZWuQST+EaVwio0IBeeAsGr2RW9JfEh7ebv3wN5y0r8ugZJ1PCt/vsQ+XiIH9i3kqCP05s8mvFeSydrl+K3kipkCgYB3j/YoASYpBqAyg5Bi3Kke4r0Fz1bRC6nGEk209WeyCXsZ7Ln3sAQuQe4xXYhjb+M4jWFccJ9nSuPahgWf8gmmbffJgdQF8Jl0F2MACRgTkhx2nfsPkEVZY4fkHDccCRwmjTVsRnl7uSE9fDHCrGfyJG1nrDBjeZYD8V9XUVp21wKBgFhBeLaEahgBSCkEBe1sTi1Hi7GYaqUKK9PvrzFA4SxiWMhJuGEM4Eq3y3HsEmDcBlEQMfY6DqpBx3CHlTx2l3t0Ivr7Qb/N7Ay3kML7yDBOEwVQW3uJOR+/PCeDb/k+MUNKf1ePMVcEqWWAFvUpmdPrB3/DpcjfnBdeG1NHDScZ
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsYqYszHEenGPDAv7D73t71NBOrxyIcKml/LwOdPPK9AlF5zglsam2fhjP0UbVGNUX3dZWXzzJzhp8Py37b83LcB2nkN80wi5Ry6lv/M2hMXuwJoas+SKyBW4oxqO/L6GCJeCXf6rlxfTPejbVva3EH0jnOGzN+hRGn+Yq0z3aFe+Woo4RBYC4PjnI0JisVVQWy9OGBxo6zUzt0JlkJJSS4VvhHdZU+/QIcke1izTV+NJZ/297RWqymreCWpjF14RuwYsVG5OSmiFfT+JTg4xVT+avX1l7c+7zdRmLNit/x/NYEFfEGO/Ul7jG89Q6t4fAUSdKA17ozhrKebMqGKJJwIDAQAB
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsYqYszHEenGPDAv7D73t71NBOrxyIcKml/LwOdPPK9AlF5zglsam2fhjP0UbVGNUX3dZWXzzJzhp8Py37b83LcB2nkN80wi5Ry6lv/M2hMXuwJoas+SKyBW4oxqO/L6GCJeCXf6rlxfTPejbVva3EH0jnOGzN+hRGn+Yq0z3aFe+Woo4RBYC4PjnI0JisVVQWy9OGBxo6zUzt0JlkJJSS4VvhHdZU+/QIcke1izTV+NJZ/297RWqymreCWpjF14RuwYsVG5OSmiFfT+JTg4xVT+avX1l7c+7zdRmLNit/x/NYEFfEGO/Ul7jG89Q6t4fAUSdKA17ozhrKebMqGKJJwIDAQAB
  serverUrl: https://openapi.alipay.com/gateway.do
  domain: https://shop.3zhit.com